/**
 * @Section Nuclear attraction integrals between different Shell-types (e.g. s, p, d, f)
 * ------------------------------------------------------------------------------------
 * The benefits of this is due to loop unrolling and compiler optimization.
 * The disadvantages is the increase in probability of error and code bloating.
 *
 * @notes Generated by "generate_integrals.py" file. With a bit of copy-pasting.
 */
#include "../include/integral_coeffs.cuh"
#include "../include/cuda_utils.cuh"

#include <stdio.h>
